# Generated by Django 5.0.6 on 2024-06-20 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gt_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='almacenamiento',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gt_store.product')),
                ('almacenamiento_tipo', models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD'), ('NVME', 'NVME')], default='SSD', max_length=60)),
                ('almacenamiento_velocidad_lectura', models.IntegerField(blank=True, null=True)),
                ('almacenamiento_velocidad_escritura', models.IntegerField(blank=True, null=True)),
                ('almacenamiento_capacidad', models.CharField(blank=True, max_length=60, null=True)),
            ],
            bases=('gt_store.product',),
        ),
        migrations.CreateModel(
            name='Audifono',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gt_store.product')),
                ('audifono_tipo_conexion', models.CharField(blank=True, max_length=60, null=True)),
                ('audifono_microfono', models.BooleanField(default=False)),
                ('audifono_tipo_auricular', models.CharField(blank=True, max_length=60, null=True)),
                ('audifono_cancelacion_ruido', models.BooleanField(default=False)),
            ],
            bases=('gt_store.product',),
        ),
        migrations.CreateModel(
            name='Fuente_poder',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gt_store.product')),
                ('fuente_poder_potencia', models.CharField(blank=True, max_length=60, null=True)),
                ('fuente_poder_certificacion', models.CharField(blank=True, max_length=60, null=True)),
                ('fuente_poder_modularidad', models.CharField(blank=True, max_length=60, null=True)),
            ],
            bases=('gt_store.product',),
        ),
        migrations.CreateModel(
            name='Gabinete',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gt_store.product')),
                ('gabinete_numero_bahias', models.IntegerField(blank=True, null=True)),
                ('gabinete_nro_ventiladores', models.IntegerField(blank=True, null=True)),
                ('gabinete_formato', models.CharField(choices=[('ATX', 'ATX'), ('Mini_ATX', 'Mini ATX'), ('Micro_ATX', 'Micro ATX')], default='ATX', max_length=50)),
            ],
            bases=('gt_store.product',),
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gt_store.product')),
                ('monitor_tamano_pantalla', models.CharField(blank=True, max_length=60, null=True)),
                ('monitor_resolucion_pantalla', models.CharField(blank=True, max_length=60, null=True)),
                ('monitor_frecuencia', models.IntegerField(blank=True, null=True)),
                ('monitor_tipo_panel', models.CharField(blank=True, max_length=60, null=True)),
            ],
            bases=('gt_store.product',),
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gt_store.product')),
                ('mouse_dpi', models.IntegerField(blank=True, null=True)),
                ('mouse_sensor', models.CharField(blank=True, max_length=60, null=True)),
                ('mouse_tipo_conexion', models.CharField(blank=True, max_length=60, null=True)),
                ('mouse_numero_botones', models.IntegerField(blank=True, null=True)),
                ('mouse_retroiluminacion', models.BooleanField(default=False)),
            ],
            bases=('gt_store.product',),
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gt_store.product')),
                ('notebook_procesador', models.CharField(blank=True, max_length=60, null=True)),
                ('notebook_memoria_ram', models.CharField(blank=True, max_length=60, null=True)),
                ('notebook_almacenamiento', models.CharField(blank=True, max_length=60, null=True)),
                ('notebook_tarjeta_video', models.CharField(blank=True, max_length=60, null=True)),
                ('notebook_tamano_pantalla', models.CharField(blank=True, max_length=60, null=True)),
                ('notebook_resolucion_pantalla', models.CharField(blank=True, max_length=60, null=True)),
                ('notebook_bateria', models.CharField(blank=True, max_length=60, null=True)),
                ('tipo_notebook', models.CharField(choices=[('notebook_gamer', 'Notebook Gamer'), ('notebook_oficina', 'Notebook Oficina')], default='notebook_gamer', max_length=60)),
            ],
            bases=('gt_store.product',),
        ),
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gt_store.product')),
                ('pc_procesador', models.CharField(blank=True, max_length=60, null=True)),
                ('pc_memoria_ram', models.CharField(blank=True, max_length=60, null=True)),
                ('pc_almacenamiento', models.CharField(blank=True, max_length=60, null=True)),
                ('pc_tarjeta_video', models.CharField(blank=True, max_length=60, null=True)),
                ('pc_fuente_poder', models.CharField(blank=True, max_length=60, null=True)),
                ('pc_placa_madre', models.CharField(blank=True, max_length=60, null=True)),
                ('pc_refrigeracion', models.CharField(blank=True, max_length=60, null=True)),
                ('pc_gabinete', models.CharField(blank=True, max_length=60, null=True)),
                ('tipo_pc', models.CharField(choices=[('pc_gamer', 'Pc Gamer'), ('pc_oficina', 'Pc Oficina')], default='pc_gamer', max_length=60)),
            ],
            bases=('gt_store.product',),
        ),
        migrations.CreateModel(
            name='Placa_madre',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gt_store.product')),
                ('placa_madre_socket', models.CharField(blank=True, max_length=60, null=True)),
                ('placa_madre_formato', models.CharField(blank=True, max_length=60, null=True)),
                ('placa_madre_chipset', models.CharField(blank=True, max_length=60, null=True)),
                ('placa_madre_soporte_ram', models.CharField(blank=True, max_length=60, null=True)),
            ],
            bases=('gt_store.product',),
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gt_store.product')),
                ('procesador_velocidad', models.CharField(blank=True, max_length=60, null=True)),
                ('procesador_nucleos', models.IntegerField(blank=True, null=True)),
                ('procesador_hilos', models.IntegerField(blank=True, null=True)),
                ('procesador_socket', models.CharField(blank=True, max_length=60, null=True)),
            ],
            bases=('gt_store.product',),
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gt_store.product')),
                ('ram_capacidad', models.CharField(blank=True, max_length=60, null=True)),
                ('ram_tipo', models.CharField(blank=True, max_length=60, null=True)),
                ('ram_velocidad', models.IntegerField(blank=True, null=True)),
                ('ram_latencia', models.CharField(blank=True, max_length=60, null=True)),
            ],
            bases=('gt_store.product',),
        ),
        migrations.CreateModel(
            name='Tarjeta_video',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gt_store.product')),
                ('tarjeta_video_memoria', models.CharField(blank=True, max_length=60, null=True)),
                ('tarjeta_video_tipo_memoria', models.CharField(blank=True, max_length=60, null=True)),
                ('tarjeta_video_velocidad_reloj', models.CharField(blank=True, max_length=60, null=True)),
                ('tarjeta_video_interfaz', models.CharField(blank=True, max_length=60, null=True)),
            ],
            bases=('gt_store.product',),
        ),
        migrations.CreateModel(
            name='Teclado',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gt_store.product')),
                ('teclado_tipo_conexion', models.CharField(blank=True, max_length=60, null=True)),
                ('teclado_tipo', models.CharField(blank=True, max_length=60, null=True)),
                ('teclado_distribucion', models.CharField(blank=True, max_length=60, null=True)),
                ('teclado_retroiluminacion', models.BooleanField(default=False)),
            ],
            bases=('gt_store.product',),
        ),
        migrations.RemoveField(
            model_name='product',
            name='almacenamiento',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bateria',
        ),
        migrations.RemoveField(
            model_name='product',
            name='boton',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cancelacion_ruido',
        ),
        migrations.RemoveField(
            model_name='product',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='product',
            name='certificacion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='chipset',
        ),
        migrations.RemoveField(
            model_name='product',
            name='distribucion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dpi',
        ),
        migrations.RemoveField(
            model_name='product',
            name='formato',
        ),
        migrations.RemoveField(
            model_name='product',
            name='frecuencia',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fuente_poder',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gabinete',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hilos',
        ),
        migrations.RemoveField(
            model_name='product',
            name='interfaz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='latencia',
        ),
        migrations.RemoveField(
            model_name='product',
            name='memoria',
        ),
        migrations.RemoveField(
            model_name='product',
            name='memoria_ram',
        ),
        migrations.RemoveField(
            model_name='product',
            name='microfono',
        ),
        migrations.RemoveField(
            model_name='product',
            name='modularidad',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nro_ventiladores',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nucleos',
        ),
        migrations.RemoveField(
            model_name='product',
            name='numero_bahias',
        ),
        migrations.RemoveField(
            model_name='product',
            name='numero_botones',
        ),
        migrations.RemoveField(
            model_name='product',
            name='placa_madre',
        ),
        migrations.RemoveField(
            model_name='product',
            name='potencia',
        ),
        migrations.RemoveField(
            model_name='product',
            name='procesador',
        ),
        migrations.RemoveField(
            model_name='product',
            name='refrigeracion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='resolucion_pantalla',
        ),
        migrations.RemoveField(
            model_name='product',
            name='retroiluminacion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='socket',
        ),
        migrations.RemoveField(
            model_name='product',
            name='soporte_ram',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tamano_pantalla',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tarjeta_video',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tipo_almacenamiento',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tipo_auricular',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tipo_conexion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tipo_memoria',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tipo_panel',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tipo_ram',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tipo_teclado',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tracking',
        ),
        migrations.RemoveField(
            model_name='product',
            name='velocidad',
        ),
        migrations.RemoveField(
            model_name='product',
            name='velocidad_escritura',
        ),
        migrations.RemoveField(
            model_name='product',
            name='velocidad_lectura',
        ),
        migrations.RemoveField(
            model_name='product',
            name='velocidad_reloj',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ventilacion',
        ),
    ]
