# Generated by Django 5.0.6 on 2024-06-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gt_store', '0002_almacenamiento_audifono_fuente_poder_gabinete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nombre_producto',
            field=models.CharField(default='nombre_producto', max_length=60),
        ),
    ]
