# Generated by Django 5.0.6 on 2024-06-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gt_store', '0003_product_nombre_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descuento',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio_anterior',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
