# Generated by Django 5.0.6 on 2024-06-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gt_store', '0004_alter_product_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descuento',
            field=models.CharField(blank=True, default=' ', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio_anterior',
            field=models.CharField(blank=True, default=' ', max_length=60, null=True),
        ),
    ]
