# Generated by Django 5.0.6 on 2024-06-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gt_store', '0005_alter_product_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
