# Generated by Django 5.0.6 on 2024-06-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gt_store', '0006_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descuento',
            field=models.IntegerField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio_anterior',
            field=models.IntegerField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio_normal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='precio_transferencia',
            field=models.IntegerField(null=True),
        ),
    ]
