# Generated by Django 5.0.6 on 2024-06-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_delete_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='password',
            field=models.CharField(default='pass', max_length=128),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='email',
            field=models.EmailField(max_length=90, unique=True),
        ),
    ]
