# Generated by Django 5.0.6 on 2024-07-08 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_perfilusuario_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='password',
            new_name='contrasena',
        ),
    ]
