# Generated by Django 5.0.6 on 2024-07-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_rename_password_perfilusuario_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='password',
            field=models.CharField(default='false', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
