# Generated by Django 5.0.6 on 2024-07-11 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_perfilusuario_is_active_perfilusuario_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='password',
        ),
    ]
