# Generated by Django 5.0.6 on 2024-07-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_comuna_region_direccion_comuna_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='comuna',
            field=models.CharField(default='comuna', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='direccion',
            name='region',
            field=models.CharField(default='comuna', max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
